### ISSUE TITLE
CCUserDefault crashing on Windows Phone 8.1 (WP8.1)

### ISSUE THREAD

**Issue by kjpou1** [mono/CocosSharp#256]
See [forum post](http://forums.xamarin.com/discussion/45172/ccuserdefault-and-windows-phone-8-1-wp8-1#latest) 

System.NotSupportedException: Specified method is not supported.
at Microsoft.Xna.Framework.Storage.ShowSelectorAsynchronousShowNoPlayer.BeginInvoke(Int32 sizeInBytes, Int32 directoryCount, AsyncCallback callback, Object object)
at Microsoft.Xna.Framework.Storage.StorageDevice.BeginShowSelector(Int32 sizeInBytes, Int32 directoryCount, AsyncCallback callback, Object state)
at CocosSharp.CCUserDefault.CheckStorageDevice()
at CocosSharp.CCUserDefault..ctor()
at CocosSharp.CCUserDefault.get_

**Comment by kjpou1** [comment]
MonoGame's StorageDevice implementation does not work on WindowsPhone 8.1.  BeginInvoke is not supported.

**Comment by kjpou1** [comment]
PR submitted to MonoGame

**Comment by kjpou1** [comment]
This has been merged in MonoGame code base.  We will get the change when we update our xamarin branch from develop branch.
